### ISSUE TITLE
How Can I use the graphql-upload with Apollo-server-lambda?

### ISSUE THREAD

**Issue by LucasBadico** [jaydenseric/apollo-upload-examples#28]
Hey Jayden,
I appreciated what you had done here with this upload example, and it is being very helpful. But I find my self stoked in how to use the graphql-upload with the apollo-server-lambda.

Can you give me any advice on how to proceed?

**Comment by mike-marcacci** [comment]
Hi @LucasBadico,

You may want to check out these issues:
- [Support AWS Lambda](https://github.com/jaydenseric/graphql-upload/issues/155)
- [Support Google Cloud Functions](https://github.com/jaydenseric/graphql-upload/issues/129)

**Comment by jaydenseric** [comment]
`apollo-server-lambda` in a way supports file uploads since v2.13.0:

- https://github.com/apollographql/apollo-server/blob/apollo-server-lambda%402.13.0/CHANGELOG.md#v2130
- https://github.com/apollographql/apollo-server/pull/3926

To get up to speed with the challenges associated with adding proper AWS Lambda support to [`graphql-upload`](https://github.com/jaydenseric/graphql-upload), please refer to the the issue @mike-marcacci already linked:

https://github.com/jaydenseric/graphql-upload/issues/155#issuecomment-632998596

If we resolve that issue we can add and maintain an AWS Lambda example here.
