### ISSUE TITLE
Read the existing data in the "upload" folder

### ISSUE THREAD

**Issue by maheraldous** [jaydenseric/apollo-upload-examples#34]
Hello @jaydenseric 

Thank you for your work. I can upload the files and then read them with query but when I started to use your package I put some files in the "upload" folder and then I tried to read them with `query`, but the answer was empty `[]`. But when I upload the files with `mutation`, I could read them with `query`.

**Comment by jaydenseric** [comment]
That is because the query resolver only looks at the metadata about the uploads in the "database". The database doesn't know about a file you manually paste into the upload folder.

While you could build a system that purely looks at the contents of a directory in the filesystem, then you would not be able to track metadata about the files such as when they were uploaded, what user uploaded it, etc. When the file is being entered into the database, that is the right time to do any expensive analysis of the file to figure out dimensions, the true MIME type (not just looking at the file extension which can be faked by the client), etc. and store it in the record.
