### ISSUE TITLE
blocked as a potential Cross-Site Request Forgery (CSRF)

### ISSUE THREAD

**Issue by rpateld** [jaydenseric/apollo-upload-examples#47]
How to fix this : 

`"This operation has been blocked as a potential Cross-Site Request Forgery (CSRF). Please either specify a 'content-type' header (with a type that is not one of application/x-www-form-urlencoded, multipart/form-data, text/plain) or provide a non-empty value for one of the following headers: x-apollo-operation-name, apollo-require-preflight\n"`

**Comment by jaydenseric** [comment]
You need to configure Apollo Client to send the security related headers that your GraphQL server requires for multipart requests. For Apollo Server, it's like this:

https://github.com/jaydenseric/apollo-upload-examples/blob/1ed805d97907c5de6bb13a6abfb52377ab0177ff/app/pages/_app.mjs#L37

Apollo has a few documentation pages and articles about these things, e.g:

https://www.apollographql.com/docs/apollo-server/security/cors/#preventing-cross-site-request-forgery-csrf

I'm assuming that this issue is for a problem you're experiencing in your own project, and not a problem running this example API and app. It was working when I tried it recently.
